### ISSUE TITLE
Smart Component support

### ISSUE THREAD

**Issue by itooth** [iKettles/framer-data-component.framerfx#12]
Hi Lan. I have just updated the Data Component package. When connected to a Smart Component and linked to a modal (just like what you've done in your example file), the Data Component stops popping up the modal. How can I achieve the detail modal popup effect in your example now?

**Comment by iKettles** [comment]
Hey @itooth could you share a link to your project with me please? You can invite me into it using my email iain@framer.com. Is it that when you tap on one of the list items the modal doesn't appear at all, or is the data in the modal not updating?

**Comment by itooth** [comment]
> Hey @itooth could you share a link to your project with me please? You can invite me into it using my email [iain@framer.com](mailto:iain@framer.com). Is it that when you tap on one of the list items the modal doesn't appear at all, or is the data in the modal not updating?

Thanks for you response. To avoid irrelevant details in my project I’ve created a toy example base on yours.: https://framer.com/projects/Data-Component-Examples-copy--lDFdTcgoRjaclZ66C3QR-hk2LF

Two things I want to achieve:
1. Detail modal page as mentioned. When I tap on one of the list items the modal doesn't appear at all. It worked just fine before updating the package.
2. Filter combination: for example, clicking on the “summer” and “$15“ buttons will show summer plants that is $15. After that, I can still perform fuzzy search base on the filtered results (just like what Pinterest does).
	
This package is really helping my project. Thanks and I’m looking for you message.

**Comment by addisonschultz** [comment]
@iKettles This is a bit of a weird issue, but I think related. 

Smart Components do seem to log/fire the `onItemTap` method when applied through overrides, IF the Smart Component is a top level Smart Component. 

It does not seem to work with nested components. 

Repro: https://framer.com/projects/Framer-Live-April-7th--eM7mBECdThTpcogmw3wY-e8tlz?node=ZXv5MFhGT

The top one contains nested components, the bottom one is just a single smart component. both have the same overrides applied, but only the bottom includes the logs as expected. This could be from what me you and Adam were talking about today?

**Comment by iKettles** [comment]
Hey @itooth, apologies for the delay in getting this fixed. Lots has changed with Smart Components which made this tough to get a fix that covered every scenario. I've just released a new version that should resolve your issue. Make sure to update the component in your project and if you still see the issue, feel free to ping me or reopen this issue. Thanks!
