### ISSUE TITLE
Can't get selected Item in DataComponent

### ISSUE THREAD

**Issue by jchaplin** [iKettles/framer-data-component.framerfx#17]
Using as a pull down list.
Cant get the selected item.

https://framer.com/projects/CarModal--fXl6mrs15OeEhTSKhaGf-1SPLt

**Comment by iKettles** [comment]
Hey @jchaplin for this to work properly, you'll need to create an event variable on your Advertiser Search Row component called `onTap`, making sure it is being used for a tap interaction on your component. The `onItemTap` should then fire as expected with the data for the selected item. Make sure to update the Data Component to the latest version to resolve some of the other layout issues you found with Smart Components :-) If you get stuck, feel free to invite me to your project as an editor!
