### ISSUE TITLE
Airtable data with nested arrays are missing

### ISSUE THREAD

**Issue by nreliu** [iKettles/framer-data-component.framerfx#8]
When I'm using the Airtable option in the component, it appears I'm not getting the full depth of data back. Some keys are missing. The component seems to only access keys that have string values. I have an Airtable table that returns arrays for certain keys in its response. This is due to some fields being relational with other tables in my Airtable base. It'd be great to have access to the full JSON from the response when used in something like the `onFormatData` callback.

Also, it appears the `id` field, which gives you the Airtable record ID is missing from the response as well.

**Comment by iKettles** [comment]
Thanks for reporting this @nreliu! I've just fixed both bugs and published a new version of the package
