### ISSUE TITLE
Option to use nested array

### ISSUE THREAD

**Issue by metehus** [iKettles/framer-data-component.framerfx#9]
So, lets say i use an API endpoint and it returns me this data:
```json
{
  "content": {
    "items": [
      {
        "foo": "bar"
      }
    ]
  }
}

```

This won't work, because it's not possible to use something like `content.items` on the **Data key** parameter.

**Comment by iKettles** [comment]
Sorry about the wait with fixing this @metehus! It's now available in the latest version of the component.
